// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package middleware

//go:generate minimock -i github.com/alonsoF100/authorization-service/internal/transport/http/middleware.TokenValidator -o token_validator_mock_test.go -n TokenValidatorMock -p middleware

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/alonsoF100/authorization-service/internal/models"
	"github.com/gojuno/minimock/v3"
)

// TokenValidatorMock implements TokenValidator
type TokenValidatorMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcValidateJWT          func(ctx context.Context, token string) (cp1 *models.Claims, err error)
	funcValidateJWTOrigin    string
	inspectFuncValidateJWT   func(ctx context.Context, token string)
	afterValidateJWTCounter  uint64
	beforeValidateJWTCounter uint64
	ValidateJWTMock          mTokenValidatorMockValidateJWT
}

// NewTokenValidatorMock returns a mock for TokenValidator
func NewTokenValidatorMock(t minimock.Tester) *TokenValidatorMock {
	m := &TokenValidatorMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.ValidateJWTMock = mTokenValidatorMockValidateJWT{mock: m}
	m.ValidateJWTMock.callArgs = []*TokenValidatorMockValidateJWTParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mTokenValidatorMockValidateJWT struct {
	optional           bool
	mock               *TokenValidatorMock
	defaultExpectation *TokenValidatorMockValidateJWTExpectation
	expectations       []*TokenValidatorMockValidateJWTExpectation

	callArgs []*TokenValidatorMockValidateJWTParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// TokenValidatorMockValidateJWTExpectation specifies expectation struct of the TokenValidator.ValidateJWT
type TokenValidatorMockValidateJWTExpectation struct {
	mock               *TokenValidatorMock
	params             *TokenValidatorMockValidateJWTParams
	paramPtrs          *TokenValidatorMockValidateJWTParamPtrs
	expectationOrigins TokenValidatorMockValidateJWTExpectationOrigins
	results            *TokenValidatorMockValidateJWTResults
	returnOrigin       string
	Counter            uint64
}

// TokenValidatorMockValidateJWTParams contains parameters of the TokenValidator.ValidateJWT
type TokenValidatorMockValidateJWTParams struct {
	ctx   context.Context
	token string
}

// TokenValidatorMockValidateJWTParamPtrs contains pointers to parameters of the TokenValidator.ValidateJWT
type TokenValidatorMockValidateJWTParamPtrs struct {
	ctx   *context.Context
	token *string
}

// TokenValidatorMockValidateJWTResults contains results of the TokenValidator.ValidateJWT
type TokenValidatorMockValidateJWTResults struct {
	cp1 *models.Claims
	err error
}

// TokenValidatorMockValidateJWTOrigins contains origins of expectations of the TokenValidator.ValidateJWT
type TokenValidatorMockValidateJWTExpectationOrigins struct {
	origin      string
	originCtx   string
	originToken string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmValidateJWT *mTokenValidatorMockValidateJWT) Optional() *mTokenValidatorMockValidateJWT {
	mmValidateJWT.optional = true
	return mmValidateJWT
}

// Expect sets up expected params for TokenValidator.ValidateJWT
func (mmValidateJWT *mTokenValidatorMockValidateJWT) Expect(ctx context.Context, token string) *mTokenValidatorMockValidateJWT {
	if mmValidateJWT.mock.funcValidateJWT != nil {
		mmValidateJWT.mock.t.Fatalf("TokenValidatorMock.ValidateJWT mock is already set by Set")
	}

	if mmValidateJWT.defaultExpectation == nil {
		mmValidateJWT.defaultExpectation = &TokenValidatorMockValidateJWTExpectation{}
	}

	if mmValidateJWT.defaultExpectation.paramPtrs != nil {
		mmValidateJWT.mock.t.Fatalf("TokenValidatorMock.ValidateJWT mock is already set by ExpectParams functions")
	}

	mmValidateJWT.defaultExpectation.params = &TokenValidatorMockValidateJWTParams{ctx, token}
	mmValidateJWT.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmValidateJWT.expectations {
		if minimock.Equal(e.params, mmValidateJWT.defaultExpectation.params) {
			mmValidateJWT.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmValidateJWT.defaultExpectation.params)
		}
	}

	return mmValidateJWT
}

// ExpectCtxParam1 sets up expected param ctx for TokenValidator.ValidateJWT
func (mmValidateJWT *mTokenValidatorMockValidateJWT) ExpectCtxParam1(ctx context.Context) *mTokenValidatorMockValidateJWT {
	if mmValidateJWT.mock.funcValidateJWT != nil {
		mmValidateJWT.mock.t.Fatalf("TokenValidatorMock.ValidateJWT mock is already set by Set")
	}

	if mmValidateJWT.defaultExpectation == nil {
		mmValidateJWT.defaultExpectation = &TokenValidatorMockValidateJWTExpectation{}
	}

	if mmValidateJWT.defaultExpectation.params != nil {
		mmValidateJWT.mock.t.Fatalf("TokenValidatorMock.ValidateJWT mock is already set by Expect")
	}

	if mmValidateJWT.defaultExpectation.paramPtrs == nil {
		mmValidateJWT.defaultExpectation.paramPtrs = &TokenValidatorMockValidateJWTParamPtrs{}
	}
	mmValidateJWT.defaultExpectation.paramPtrs.ctx = &ctx
	mmValidateJWT.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmValidateJWT
}

// ExpectTokenParam2 sets up expected param token for TokenValidator.ValidateJWT
func (mmValidateJWT *mTokenValidatorMockValidateJWT) ExpectTokenParam2(token string) *mTokenValidatorMockValidateJWT {
	if mmValidateJWT.mock.funcValidateJWT != nil {
		mmValidateJWT.mock.t.Fatalf("TokenValidatorMock.ValidateJWT mock is already set by Set")
	}

	if mmValidateJWT.defaultExpectation == nil {
		mmValidateJWT.defaultExpectation = &TokenValidatorMockValidateJWTExpectation{}
	}

	if mmValidateJWT.defaultExpectation.params != nil {
		mmValidateJWT.mock.t.Fatalf("TokenValidatorMock.ValidateJWT mock is already set by Expect")
	}

	if mmValidateJWT.defaultExpectation.paramPtrs == nil {
		mmValidateJWT.defaultExpectation.paramPtrs = &TokenValidatorMockValidateJWTParamPtrs{}
	}
	mmValidateJWT.defaultExpectation.paramPtrs.token = &token
	mmValidateJWT.defaultExpectation.expectationOrigins.originToken = minimock.CallerInfo(1)

	return mmValidateJWT
}

// Inspect accepts an inspector function that has same arguments as the TokenValidator.ValidateJWT
func (mmValidateJWT *mTokenValidatorMockValidateJWT) Inspect(f func(ctx context.Context, token string)) *mTokenValidatorMockValidateJWT {
	if mmValidateJWT.mock.inspectFuncValidateJWT != nil {
		mmValidateJWT.mock.t.Fatalf("Inspect function is already set for TokenValidatorMock.ValidateJWT")
	}

	mmValidateJWT.mock.inspectFuncValidateJWT = f

	return mmValidateJWT
}

// Return sets up results that will be returned by TokenValidator.ValidateJWT
func (mmValidateJWT *mTokenValidatorMockValidateJWT) Return(cp1 *models.Claims, err error) *TokenValidatorMock {
	if mmValidateJWT.mock.funcValidateJWT != nil {
		mmValidateJWT.mock.t.Fatalf("TokenValidatorMock.ValidateJWT mock is already set by Set")
	}

	if mmValidateJWT.defaultExpectation == nil {
		mmValidateJWT.defaultExpectation = &TokenValidatorMockValidateJWTExpectation{mock: mmValidateJWT.mock}
	}
	mmValidateJWT.defaultExpectation.results = &TokenValidatorMockValidateJWTResults{cp1, err}
	mmValidateJWT.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmValidateJWT.mock
}

// Set uses given function f to mock the TokenValidator.ValidateJWT method
func (mmValidateJWT *mTokenValidatorMockValidateJWT) Set(f func(ctx context.Context, token string) (cp1 *models.Claims, err error)) *TokenValidatorMock {
	if mmValidateJWT.defaultExpectation != nil {
		mmValidateJWT.mock.t.Fatalf("Default expectation is already set for the TokenValidator.ValidateJWT method")
	}

	if len(mmValidateJWT.expectations) > 0 {
		mmValidateJWT.mock.t.Fatalf("Some expectations are already set for the TokenValidator.ValidateJWT method")
	}

	mmValidateJWT.mock.funcValidateJWT = f
	mmValidateJWT.mock.funcValidateJWTOrigin = minimock.CallerInfo(1)
	return mmValidateJWT.mock
}

// When sets expectation for the TokenValidator.ValidateJWT which will trigger the result defined by the following
// Then helper
func (mmValidateJWT *mTokenValidatorMockValidateJWT) When(ctx context.Context, token string) *TokenValidatorMockValidateJWTExpectation {
	if mmValidateJWT.mock.funcValidateJWT != nil {
		mmValidateJWT.mock.t.Fatalf("TokenValidatorMock.ValidateJWT mock is already set by Set")
	}

	expectation := &TokenValidatorMockValidateJWTExpectation{
		mock:               mmValidateJWT.mock,
		params:             &TokenValidatorMockValidateJWTParams{ctx, token},
		expectationOrigins: TokenValidatorMockValidateJWTExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmValidateJWT.expectations = append(mmValidateJWT.expectations, expectation)
	return expectation
}

// Then sets up TokenValidator.ValidateJWT return parameters for the expectation previously defined by the When method
func (e *TokenValidatorMockValidateJWTExpectation) Then(cp1 *models.Claims, err error) *TokenValidatorMock {
	e.results = &TokenValidatorMockValidateJWTResults{cp1, err}
	return e.mock
}

// Times sets number of times TokenValidator.ValidateJWT should be invoked
func (mmValidateJWT *mTokenValidatorMockValidateJWT) Times(n uint64) *mTokenValidatorMockValidateJWT {
	if n == 0 {
		mmValidateJWT.mock.t.Fatalf("Times of TokenValidatorMock.ValidateJWT mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmValidateJWT.expectedInvocations, n)
	mmValidateJWT.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmValidateJWT
}

func (mmValidateJWT *mTokenValidatorMockValidateJWT) invocationsDone() bool {
	if len(mmValidateJWT.expectations) == 0 && mmValidateJWT.defaultExpectation == nil && mmValidateJWT.mock.funcValidateJWT == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmValidateJWT.mock.afterValidateJWTCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmValidateJWT.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// ValidateJWT implements TokenValidator
func (mmValidateJWT *TokenValidatorMock) ValidateJWT(ctx context.Context, token string) (cp1 *models.Claims, err error) {
	mm_atomic.AddUint64(&mmValidateJWT.beforeValidateJWTCounter, 1)
	defer mm_atomic.AddUint64(&mmValidateJWT.afterValidateJWTCounter, 1)

	mmValidateJWT.t.Helper()

	if mmValidateJWT.inspectFuncValidateJWT != nil {
		mmValidateJWT.inspectFuncValidateJWT(ctx, token)
	}

	mm_params := TokenValidatorMockValidateJWTParams{ctx, token}

	// Record call args
	mmValidateJWT.ValidateJWTMock.mutex.Lock()
	mmValidateJWT.ValidateJWTMock.callArgs = append(mmValidateJWT.ValidateJWTMock.callArgs, &mm_params)
	mmValidateJWT.ValidateJWTMock.mutex.Unlock()

	for _, e := range mmValidateJWT.ValidateJWTMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.cp1, e.results.err
		}
	}

	if mmValidateJWT.ValidateJWTMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmValidateJWT.ValidateJWTMock.defaultExpectation.Counter, 1)
		mm_want := mmValidateJWT.ValidateJWTMock.defaultExpectation.params
		mm_want_ptrs := mmValidateJWT.ValidateJWTMock.defaultExpectation.paramPtrs

		mm_got := TokenValidatorMockValidateJWTParams{ctx, token}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmValidateJWT.t.Errorf("TokenValidatorMock.ValidateJWT got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmValidateJWT.ValidateJWTMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.token != nil && !minimock.Equal(*mm_want_ptrs.token, mm_got.token) {
				mmValidateJWT.t.Errorf("TokenValidatorMock.ValidateJWT got unexpected parameter token, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmValidateJWT.ValidateJWTMock.defaultExpectation.expectationOrigins.originToken, *mm_want_ptrs.token, mm_got.token, minimock.Diff(*mm_want_ptrs.token, mm_got.token))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmValidateJWT.t.Errorf("TokenValidatorMock.ValidateJWT got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmValidateJWT.ValidateJWTMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmValidateJWT.ValidateJWTMock.defaultExpectation.results
		if mm_results == nil {
			mmValidateJWT.t.Fatal("No results are set for the TokenValidatorMock.ValidateJWT")
		}
		return (*mm_results).cp1, (*mm_results).err
	}
	if mmValidateJWT.funcValidateJWT != nil {
		return mmValidateJWT.funcValidateJWT(ctx, token)
	}
	mmValidateJWT.t.Fatalf("Unexpected call to TokenValidatorMock.ValidateJWT. %v %v", ctx, token)
	return
}

// ValidateJWTAfterCounter returns a count of finished TokenValidatorMock.ValidateJWT invocations
func (mmValidateJWT *TokenValidatorMock) ValidateJWTAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateJWT.afterValidateJWTCounter)
}

// ValidateJWTBeforeCounter returns a count of TokenValidatorMock.ValidateJWT invocations
func (mmValidateJWT *TokenValidatorMock) ValidateJWTBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmValidateJWT.beforeValidateJWTCounter)
}

// Calls returns a list of arguments used in each call to TokenValidatorMock.ValidateJWT.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmValidateJWT *mTokenValidatorMockValidateJWT) Calls() []*TokenValidatorMockValidateJWTParams {
	mmValidateJWT.mutex.RLock()

	argCopy := make([]*TokenValidatorMockValidateJWTParams, len(mmValidateJWT.callArgs))
	copy(argCopy, mmValidateJWT.callArgs)

	mmValidateJWT.mutex.RUnlock()

	return argCopy
}

// MinimockValidateJWTDone returns true if the count of the ValidateJWT invocations corresponds
// the number of defined expectations
func (m *TokenValidatorMock) MinimockValidateJWTDone() bool {
	if m.ValidateJWTMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.ValidateJWTMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.ValidateJWTMock.invocationsDone()
}

// MinimockValidateJWTInspect logs each unmet expectation
func (m *TokenValidatorMock) MinimockValidateJWTInspect() {
	for _, e := range m.ValidateJWTMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to TokenValidatorMock.ValidateJWT at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterValidateJWTCounter := mm_atomic.LoadUint64(&m.afterValidateJWTCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.ValidateJWTMock.defaultExpectation != nil && afterValidateJWTCounter < 1 {
		if m.ValidateJWTMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to TokenValidatorMock.ValidateJWT at\n%s", m.ValidateJWTMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to TokenValidatorMock.ValidateJWT at\n%s with params: %#v", m.ValidateJWTMock.defaultExpectation.expectationOrigins.origin, *m.ValidateJWTMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcValidateJWT != nil && afterValidateJWTCounter < 1 {
		m.t.Errorf("Expected call to TokenValidatorMock.ValidateJWT at\n%s", m.funcValidateJWTOrigin)
	}

	if !m.ValidateJWTMock.invocationsDone() && afterValidateJWTCounter > 0 {
		m.t.Errorf("Expected %d calls to TokenValidatorMock.ValidateJWT at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.ValidateJWTMock.expectedInvocations), m.ValidateJWTMock.expectedInvocationsOrigin, afterValidateJWTCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *TokenValidatorMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockValidateJWTInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *TokenValidatorMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *TokenValidatorMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockValidateJWTDone()
}
