// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package service

//go:generate minimock -i github.com/alonsoF100/authorization-service/internal/service.AuthRepository -o auth_repository_mock_test.go -n AuthRepositoryMock -p service

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/alonsoF100/authorization-service/internal/models"
	"github.com/gojuno/minimock/v3"
)

// AuthRepositoryMock implements AuthRepository
type AuthRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateUser          func(ctx context.Context, user *models.User) (up1 *models.User, err error)
	funcCreateUserOrigin    string
	inspectFuncCreateUser   func(ctx context.Context, user *models.User)
	afterCreateUserCounter  uint64
	beforeCreateUserCounter uint64
	CreateUserMock          mAuthRepositoryMockCreateUser

	funcFindByEmail          func(ctx context.Context, email string) (up1 *models.User, err error)
	funcFindByEmailOrigin    string
	inspectFuncFindByEmail   func(ctx context.Context, email string)
	afterFindByEmailCounter  uint64
	beforeFindByEmailCounter uint64
	FindByEmailMock          mAuthRepositoryMockFindByEmail
}

// NewAuthRepositoryMock returns a mock for AuthRepository
func NewAuthRepositoryMock(t minimock.Tester) *AuthRepositoryMock {
	m := &AuthRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateUserMock = mAuthRepositoryMockCreateUser{mock: m}
	m.CreateUserMock.callArgs = []*AuthRepositoryMockCreateUserParams{}

	m.FindByEmailMock = mAuthRepositoryMockFindByEmail{mock: m}
	m.FindByEmailMock.callArgs = []*AuthRepositoryMockFindByEmailParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mAuthRepositoryMockCreateUser struct {
	optional           bool
	mock               *AuthRepositoryMock
	defaultExpectation *AuthRepositoryMockCreateUserExpectation
	expectations       []*AuthRepositoryMockCreateUserExpectation

	callArgs []*AuthRepositoryMockCreateUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthRepositoryMockCreateUserExpectation specifies expectation struct of the AuthRepository.CreateUser
type AuthRepositoryMockCreateUserExpectation struct {
	mock               *AuthRepositoryMock
	params             *AuthRepositoryMockCreateUserParams
	paramPtrs          *AuthRepositoryMockCreateUserParamPtrs
	expectationOrigins AuthRepositoryMockCreateUserExpectationOrigins
	results            *AuthRepositoryMockCreateUserResults
	returnOrigin       string
	Counter            uint64
}

// AuthRepositoryMockCreateUserParams contains parameters of the AuthRepository.CreateUser
type AuthRepositoryMockCreateUserParams struct {
	ctx  context.Context
	user *models.User
}

// AuthRepositoryMockCreateUserParamPtrs contains pointers to parameters of the AuthRepository.CreateUser
type AuthRepositoryMockCreateUserParamPtrs struct {
	ctx  *context.Context
	user **models.User
}

// AuthRepositoryMockCreateUserResults contains results of the AuthRepository.CreateUser
type AuthRepositoryMockCreateUserResults struct {
	up1 *models.User
	err error
}

// AuthRepositoryMockCreateUserOrigins contains origins of expectations of the AuthRepository.CreateUser
type AuthRepositoryMockCreateUserExpectationOrigins struct {
	origin     string
	originCtx  string
	originUser string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateUser *mAuthRepositoryMockCreateUser) Optional() *mAuthRepositoryMockCreateUser {
	mmCreateUser.optional = true
	return mmCreateUser
}

// Expect sets up expected params for AuthRepository.CreateUser
func (mmCreateUser *mAuthRepositoryMockCreateUser) Expect(ctx context.Context, user *models.User) *mAuthRepositoryMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthRepositoryMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &AuthRepositoryMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.paramPtrs != nil {
		mmCreateUser.mock.t.Fatalf("AuthRepositoryMock.CreateUser mock is already set by ExpectParams functions")
	}

	mmCreateUser.defaultExpectation.params = &AuthRepositoryMockCreateUserParams{ctx, user}
	mmCreateUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateUser.expectations {
		if minimock.Equal(e.params, mmCreateUser.defaultExpectation.params) {
			mmCreateUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateUser.defaultExpectation.params)
		}
	}

	return mmCreateUser
}

// ExpectCtxParam1 sets up expected param ctx for AuthRepository.CreateUser
func (mmCreateUser *mAuthRepositoryMockCreateUser) ExpectCtxParam1(ctx context.Context) *mAuthRepositoryMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthRepositoryMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &AuthRepositoryMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("AuthRepositoryMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &AuthRepositoryMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateUser
}

// ExpectUserParam2 sets up expected param user for AuthRepository.CreateUser
func (mmCreateUser *mAuthRepositoryMockCreateUser) ExpectUserParam2(user *models.User) *mAuthRepositoryMockCreateUser {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthRepositoryMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &AuthRepositoryMockCreateUserExpectation{}
	}

	if mmCreateUser.defaultExpectation.params != nil {
		mmCreateUser.mock.t.Fatalf("AuthRepositoryMock.CreateUser mock is already set by Expect")
	}

	if mmCreateUser.defaultExpectation.paramPtrs == nil {
		mmCreateUser.defaultExpectation.paramPtrs = &AuthRepositoryMockCreateUserParamPtrs{}
	}
	mmCreateUser.defaultExpectation.paramPtrs.user = &user
	mmCreateUser.defaultExpectation.expectationOrigins.originUser = minimock.CallerInfo(1)

	return mmCreateUser
}

// Inspect accepts an inspector function that has same arguments as the AuthRepository.CreateUser
func (mmCreateUser *mAuthRepositoryMockCreateUser) Inspect(f func(ctx context.Context, user *models.User)) *mAuthRepositoryMockCreateUser {
	if mmCreateUser.mock.inspectFuncCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("Inspect function is already set for AuthRepositoryMock.CreateUser")
	}

	mmCreateUser.mock.inspectFuncCreateUser = f

	return mmCreateUser
}

// Return sets up results that will be returned by AuthRepository.CreateUser
func (mmCreateUser *mAuthRepositoryMockCreateUser) Return(up1 *models.User, err error) *AuthRepositoryMock {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthRepositoryMock.CreateUser mock is already set by Set")
	}

	if mmCreateUser.defaultExpectation == nil {
		mmCreateUser.defaultExpectation = &AuthRepositoryMockCreateUserExpectation{mock: mmCreateUser.mock}
	}
	mmCreateUser.defaultExpectation.results = &AuthRepositoryMockCreateUserResults{up1, err}
	mmCreateUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateUser.mock
}

// Set uses given function f to mock the AuthRepository.CreateUser method
func (mmCreateUser *mAuthRepositoryMockCreateUser) Set(f func(ctx context.Context, user *models.User) (up1 *models.User, err error)) *AuthRepositoryMock {
	if mmCreateUser.defaultExpectation != nil {
		mmCreateUser.mock.t.Fatalf("Default expectation is already set for the AuthRepository.CreateUser method")
	}

	if len(mmCreateUser.expectations) > 0 {
		mmCreateUser.mock.t.Fatalf("Some expectations are already set for the AuthRepository.CreateUser method")
	}

	mmCreateUser.mock.funcCreateUser = f
	mmCreateUser.mock.funcCreateUserOrigin = minimock.CallerInfo(1)
	return mmCreateUser.mock
}

// When sets expectation for the AuthRepository.CreateUser which will trigger the result defined by the following
// Then helper
func (mmCreateUser *mAuthRepositoryMockCreateUser) When(ctx context.Context, user *models.User) *AuthRepositoryMockCreateUserExpectation {
	if mmCreateUser.mock.funcCreateUser != nil {
		mmCreateUser.mock.t.Fatalf("AuthRepositoryMock.CreateUser mock is already set by Set")
	}

	expectation := &AuthRepositoryMockCreateUserExpectation{
		mock:               mmCreateUser.mock,
		params:             &AuthRepositoryMockCreateUserParams{ctx, user},
		expectationOrigins: AuthRepositoryMockCreateUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateUser.expectations = append(mmCreateUser.expectations, expectation)
	return expectation
}

// Then sets up AuthRepository.CreateUser return parameters for the expectation previously defined by the When method
func (e *AuthRepositoryMockCreateUserExpectation) Then(up1 *models.User, err error) *AuthRepositoryMock {
	e.results = &AuthRepositoryMockCreateUserResults{up1, err}
	return e.mock
}

// Times sets number of times AuthRepository.CreateUser should be invoked
func (mmCreateUser *mAuthRepositoryMockCreateUser) Times(n uint64) *mAuthRepositoryMockCreateUser {
	if n == 0 {
		mmCreateUser.mock.t.Fatalf("Times of AuthRepositoryMock.CreateUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateUser.expectedInvocations, n)
	mmCreateUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateUser
}

func (mmCreateUser *mAuthRepositoryMockCreateUser) invocationsDone() bool {
	if len(mmCreateUser.expectations) == 0 && mmCreateUser.defaultExpectation == nil && mmCreateUser.mock.funcCreateUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateUser.mock.afterCreateUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateUser implements AuthRepository
func (mmCreateUser *AuthRepositoryMock) CreateUser(ctx context.Context, user *models.User) (up1 *models.User, err error) {
	mm_atomic.AddUint64(&mmCreateUser.beforeCreateUserCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateUser.afterCreateUserCounter, 1)

	mmCreateUser.t.Helper()

	if mmCreateUser.inspectFuncCreateUser != nil {
		mmCreateUser.inspectFuncCreateUser(ctx, user)
	}

	mm_params := AuthRepositoryMockCreateUserParams{ctx, user}

	// Record call args
	mmCreateUser.CreateUserMock.mutex.Lock()
	mmCreateUser.CreateUserMock.callArgs = append(mmCreateUser.CreateUserMock.callArgs, &mm_params)
	mmCreateUser.CreateUserMock.mutex.Unlock()

	for _, e := range mmCreateUser.CreateUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmCreateUser.CreateUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateUser.CreateUserMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateUser.CreateUserMock.defaultExpectation.params
		mm_want_ptrs := mmCreateUser.CreateUserMock.defaultExpectation.paramPtrs

		mm_got := AuthRepositoryMockCreateUserParams{ctx, user}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateUser.t.Errorf("AuthRepositoryMock.CreateUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.user != nil && !minimock.Equal(*mm_want_ptrs.user, mm_got.user) {
				mmCreateUser.t.Errorf("AuthRepositoryMock.CreateUser got unexpected parameter user, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.originUser, *mm_want_ptrs.user, mm_got.user, minimock.Diff(*mm_want_ptrs.user, mm_got.user))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateUser.t.Errorf("AuthRepositoryMock.CreateUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateUser.CreateUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateUser.CreateUserMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateUser.t.Fatal("No results are set for the AuthRepositoryMock.CreateUser")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmCreateUser.funcCreateUser != nil {
		return mmCreateUser.funcCreateUser(ctx, user)
	}
	mmCreateUser.t.Fatalf("Unexpected call to AuthRepositoryMock.CreateUser. %v %v", ctx, user)
	return
}

// CreateUserAfterCounter returns a count of finished AuthRepositoryMock.CreateUser invocations
func (mmCreateUser *AuthRepositoryMock) CreateUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateUser.afterCreateUserCounter)
}

// CreateUserBeforeCounter returns a count of AuthRepositoryMock.CreateUser invocations
func (mmCreateUser *AuthRepositoryMock) CreateUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateUser.beforeCreateUserCounter)
}

// Calls returns a list of arguments used in each call to AuthRepositoryMock.CreateUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateUser *mAuthRepositoryMockCreateUser) Calls() []*AuthRepositoryMockCreateUserParams {
	mmCreateUser.mutex.RLock()

	argCopy := make([]*AuthRepositoryMockCreateUserParams, len(mmCreateUser.callArgs))
	copy(argCopy, mmCreateUser.callArgs)

	mmCreateUser.mutex.RUnlock()

	return argCopy
}

// MinimockCreateUserDone returns true if the count of the CreateUser invocations corresponds
// the number of defined expectations
func (m *AuthRepositoryMock) MinimockCreateUserDone() bool {
	if m.CreateUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateUserMock.invocationsDone()
}

// MinimockCreateUserInspect logs each unmet expectation
func (m *AuthRepositoryMock) MinimockCreateUserInspect() {
	for _, e := range m.CreateUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthRepositoryMock.CreateUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateUserCounter := mm_atomic.LoadUint64(&m.afterCreateUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateUserMock.defaultExpectation != nil && afterCreateUserCounter < 1 {
		if m.CreateUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthRepositoryMock.CreateUser at\n%s", m.CreateUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthRepositoryMock.CreateUser at\n%s with params: %#v", m.CreateUserMock.defaultExpectation.expectationOrigins.origin, *m.CreateUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateUser != nil && afterCreateUserCounter < 1 {
		m.t.Errorf("Expected call to AuthRepositoryMock.CreateUser at\n%s", m.funcCreateUserOrigin)
	}

	if !m.CreateUserMock.invocationsDone() && afterCreateUserCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthRepositoryMock.CreateUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateUserMock.expectedInvocations), m.CreateUserMock.expectedInvocationsOrigin, afterCreateUserCounter)
	}
}

type mAuthRepositoryMockFindByEmail struct {
	optional           bool
	mock               *AuthRepositoryMock
	defaultExpectation *AuthRepositoryMockFindByEmailExpectation
	expectations       []*AuthRepositoryMockFindByEmailExpectation

	callArgs []*AuthRepositoryMockFindByEmailParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// AuthRepositoryMockFindByEmailExpectation specifies expectation struct of the AuthRepository.FindByEmail
type AuthRepositoryMockFindByEmailExpectation struct {
	mock               *AuthRepositoryMock
	params             *AuthRepositoryMockFindByEmailParams
	paramPtrs          *AuthRepositoryMockFindByEmailParamPtrs
	expectationOrigins AuthRepositoryMockFindByEmailExpectationOrigins
	results            *AuthRepositoryMockFindByEmailResults
	returnOrigin       string
	Counter            uint64
}

// AuthRepositoryMockFindByEmailParams contains parameters of the AuthRepository.FindByEmail
type AuthRepositoryMockFindByEmailParams struct {
	ctx   context.Context
	email string
}

// AuthRepositoryMockFindByEmailParamPtrs contains pointers to parameters of the AuthRepository.FindByEmail
type AuthRepositoryMockFindByEmailParamPtrs struct {
	ctx   *context.Context
	email *string
}

// AuthRepositoryMockFindByEmailResults contains results of the AuthRepository.FindByEmail
type AuthRepositoryMockFindByEmailResults struct {
	up1 *models.User
	err error
}

// AuthRepositoryMockFindByEmailOrigins contains origins of expectations of the AuthRepository.FindByEmail
type AuthRepositoryMockFindByEmailExpectationOrigins struct {
	origin      string
	originCtx   string
	originEmail string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmFindByEmail *mAuthRepositoryMockFindByEmail) Optional() *mAuthRepositoryMockFindByEmail {
	mmFindByEmail.optional = true
	return mmFindByEmail
}

// Expect sets up expected params for AuthRepository.FindByEmail
func (mmFindByEmail *mAuthRepositoryMockFindByEmail) Expect(ctx context.Context, email string) *mAuthRepositoryMockFindByEmail {
	if mmFindByEmail.mock.funcFindByEmail != nil {
		mmFindByEmail.mock.t.Fatalf("AuthRepositoryMock.FindByEmail mock is already set by Set")
	}

	if mmFindByEmail.defaultExpectation == nil {
		mmFindByEmail.defaultExpectation = &AuthRepositoryMockFindByEmailExpectation{}
	}

	if mmFindByEmail.defaultExpectation.paramPtrs != nil {
		mmFindByEmail.mock.t.Fatalf("AuthRepositoryMock.FindByEmail mock is already set by ExpectParams functions")
	}

	mmFindByEmail.defaultExpectation.params = &AuthRepositoryMockFindByEmailParams{ctx, email}
	mmFindByEmail.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmFindByEmail.expectations {
		if minimock.Equal(e.params, mmFindByEmail.defaultExpectation.params) {
			mmFindByEmail.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFindByEmail.defaultExpectation.params)
		}
	}

	return mmFindByEmail
}

// ExpectCtxParam1 sets up expected param ctx for AuthRepository.FindByEmail
func (mmFindByEmail *mAuthRepositoryMockFindByEmail) ExpectCtxParam1(ctx context.Context) *mAuthRepositoryMockFindByEmail {
	if mmFindByEmail.mock.funcFindByEmail != nil {
		mmFindByEmail.mock.t.Fatalf("AuthRepositoryMock.FindByEmail mock is already set by Set")
	}

	if mmFindByEmail.defaultExpectation == nil {
		mmFindByEmail.defaultExpectation = &AuthRepositoryMockFindByEmailExpectation{}
	}

	if mmFindByEmail.defaultExpectation.params != nil {
		mmFindByEmail.mock.t.Fatalf("AuthRepositoryMock.FindByEmail mock is already set by Expect")
	}

	if mmFindByEmail.defaultExpectation.paramPtrs == nil {
		mmFindByEmail.defaultExpectation.paramPtrs = &AuthRepositoryMockFindByEmailParamPtrs{}
	}
	mmFindByEmail.defaultExpectation.paramPtrs.ctx = &ctx
	mmFindByEmail.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmFindByEmail
}

// ExpectEmailParam2 sets up expected param email for AuthRepository.FindByEmail
func (mmFindByEmail *mAuthRepositoryMockFindByEmail) ExpectEmailParam2(email string) *mAuthRepositoryMockFindByEmail {
	if mmFindByEmail.mock.funcFindByEmail != nil {
		mmFindByEmail.mock.t.Fatalf("AuthRepositoryMock.FindByEmail mock is already set by Set")
	}

	if mmFindByEmail.defaultExpectation == nil {
		mmFindByEmail.defaultExpectation = &AuthRepositoryMockFindByEmailExpectation{}
	}

	if mmFindByEmail.defaultExpectation.params != nil {
		mmFindByEmail.mock.t.Fatalf("AuthRepositoryMock.FindByEmail mock is already set by Expect")
	}

	if mmFindByEmail.defaultExpectation.paramPtrs == nil {
		mmFindByEmail.defaultExpectation.paramPtrs = &AuthRepositoryMockFindByEmailParamPtrs{}
	}
	mmFindByEmail.defaultExpectation.paramPtrs.email = &email
	mmFindByEmail.defaultExpectation.expectationOrigins.originEmail = minimock.CallerInfo(1)

	return mmFindByEmail
}

// Inspect accepts an inspector function that has same arguments as the AuthRepository.FindByEmail
func (mmFindByEmail *mAuthRepositoryMockFindByEmail) Inspect(f func(ctx context.Context, email string)) *mAuthRepositoryMockFindByEmail {
	if mmFindByEmail.mock.inspectFuncFindByEmail != nil {
		mmFindByEmail.mock.t.Fatalf("Inspect function is already set for AuthRepositoryMock.FindByEmail")
	}

	mmFindByEmail.mock.inspectFuncFindByEmail = f

	return mmFindByEmail
}

// Return sets up results that will be returned by AuthRepository.FindByEmail
func (mmFindByEmail *mAuthRepositoryMockFindByEmail) Return(up1 *models.User, err error) *AuthRepositoryMock {
	if mmFindByEmail.mock.funcFindByEmail != nil {
		mmFindByEmail.mock.t.Fatalf("AuthRepositoryMock.FindByEmail mock is already set by Set")
	}

	if mmFindByEmail.defaultExpectation == nil {
		mmFindByEmail.defaultExpectation = &AuthRepositoryMockFindByEmailExpectation{mock: mmFindByEmail.mock}
	}
	mmFindByEmail.defaultExpectation.results = &AuthRepositoryMockFindByEmailResults{up1, err}
	mmFindByEmail.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmFindByEmail.mock
}

// Set uses given function f to mock the AuthRepository.FindByEmail method
func (mmFindByEmail *mAuthRepositoryMockFindByEmail) Set(f func(ctx context.Context, email string) (up1 *models.User, err error)) *AuthRepositoryMock {
	if mmFindByEmail.defaultExpectation != nil {
		mmFindByEmail.mock.t.Fatalf("Default expectation is already set for the AuthRepository.FindByEmail method")
	}

	if len(mmFindByEmail.expectations) > 0 {
		mmFindByEmail.mock.t.Fatalf("Some expectations are already set for the AuthRepository.FindByEmail method")
	}

	mmFindByEmail.mock.funcFindByEmail = f
	mmFindByEmail.mock.funcFindByEmailOrigin = minimock.CallerInfo(1)
	return mmFindByEmail.mock
}

// When sets expectation for the AuthRepository.FindByEmail which will trigger the result defined by the following
// Then helper
func (mmFindByEmail *mAuthRepositoryMockFindByEmail) When(ctx context.Context, email string) *AuthRepositoryMockFindByEmailExpectation {
	if mmFindByEmail.mock.funcFindByEmail != nil {
		mmFindByEmail.mock.t.Fatalf("AuthRepositoryMock.FindByEmail mock is already set by Set")
	}

	expectation := &AuthRepositoryMockFindByEmailExpectation{
		mock:               mmFindByEmail.mock,
		params:             &AuthRepositoryMockFindByEmailParams{ctx, email},
		expectationOrigins: AuthRepositoryMockFindByEmailExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmFindByEmail.expectations = append(mmFindByEmail.expectations, expectation)
	return expectation
}

// Then sets up AuthRepository.FindByEmail return parameters for the expectation previously defined by the When method
func (e *AuthRepositoryMockFindByEmailExpectation) Then(up1 *models.User, err error) *AuthRepositoryMock {
	e.results = &AuthRepositoryMockFindByEmailResults{up1, err}
	return e.mock
}

// Times sets number of times AuthRepository.FindByEmail should be invoked
func (mmFindByEmail *mAuthRepositoryMockFindByEmail) Times(n uint64) *mAuthRepositoryMockFindByEmail {
	if n == 0 {
		mmFindByEmail.mock.t.Fatalf("Times of AuthRepositoryMock.FindByEmail mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmFindByEmail.expectedInvocations, n)
	mmFindByEmail.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmFindByEmail
}

func (mmFindByEmail *mAuthRepositoryMockFindByEmail) invocationsDone() bool {
	if len(mmFindByEmail.expectations) == 0 && mmFindByEmail.defaultExpectation == nil && mmFindByEmail.mock.funcFindByEmail == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmFindByEmail.mock.afterFindByEmailCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmFindByEmail.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// FindByEmail implements AuthRepository
func (mmFindByEmail *AuthRepositoryMock) FindByEmail(ctx context.Context, email string) (up1 *models.User, err error) {
	mm_atomic.AddUint64(&mmFindByEmail.beforeFindByEmailCounter, 1)
	defer mm_atomic.AddUint64(&mmFindByEmail.afterFindByEmailCounter, 1)

	mmFindByEmail.t.Helper()

	if mmFindByEmail.inspectFuncFindByEmail != nil {
		mmFindByEmail.inspectFuncFindByEmail(ctx, email)
	}

	mm_params := AuthRepositoryMockFindByEmailParams{ctx, email}

	// Record call args
	mmFindByEmail.FindByEmailMock.mutex.Lock()
	mmFindByEmail.FindByEmailMock.callArgs = append(mmFindByEmail.FindByEmailMock.callArgs, &mm_params)
	mmFindByEmail.FindByEmailMock.mutex.Unlock()

	for _, e := range mmFindByEmail.FindByEmailMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmFindByEmail.FindByEmailMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFindByEmail.FindByEmailMock.defaultExpectation.Counter, 1)
		mm_want := mmFindByEmail.FindByEmailMock.defaultExpectation.params
		mm_want_ptrs := mmFindByEmail.FindByEmailMock.defaultExpectation.paramPtrs

		mm_got := AuthRepositoryMockFindByEmailParams{ctx, email}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmFindByEmail.t.Errorf("AuthRepositoryMock.FindByEmail got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFindByEmail.FindByEmailMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.email != nil && !minimock.Equal(*mm_want_ptrs.email, mm_got.email) {
				mmFindByEmail.t.Errorf("AuthRepositoryMock.FindByEmail got unexpected parameter email, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFindByEmail.FindByEmailMock.defaultExpectation.expectationOrigins.originEmail, *mm_want_ptrs.email, mm_got.email, minimock.Diff(*mm_want_ptrs.email, mm_got.email))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmFindByEmail.t.Errorf("AuthRepositoryMock.FindByEmail got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmFindByEmail.FindByEmailMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmFindByEmail.FindByEmailMock.defaultExpectation.results
		if mm_results == nil {
			mmFindByEmail.t.Fatal("No results are set for the AuthRepositoryMock.FindByEmail")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmFindByEmail.funcFindByEmail != nil {
		return mmFindByEmail.funcFindByEmail(ctx, email)
	}
	mmFindByEmail.t.Fatalf("Unexpected call to AuthRepositoryMock.FindByEmail. %v %v", ctx, email)
	return
}

// FindByEmailAfterCounter returns a count of finished AuthRepositoryMock.FindByEmail invocations
func (mmFindByEmail *AuthRepositoryMock) FindByEmailAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFindByEmail.afterFindByEmailCounter)
}

// FindByEmailBeforeCounter returns a count of AuthRepositoryMock.FindByEmail invocations
func (mmFindByEmail *AuthRepositoryMock) FindByEmailBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFindByEmail.beforeFindByEmailCounter)
}

// Calls returns a list of arguments used in each call to AuthRepositoryMock.FindByEmail.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFindByEmail *mAuthRepositoryMockFindByEmail) Calls() []*AuthRepositoryMockFindByEmailParams {
	mmFindByEmail.mutex.RLock()

	argCopy := make([]*AuthRepositoryMockFindByEmailParams, len(mmFindByEmail.callArgs))
	copy(argCopy, mmFindByEmail.callArgs)

	mmFindByEmail.mutex.RUnlock()

	return argCopy
}

// MinimockFindByEmailDone returns true if the count of the FindByEmail invocations corresponds
// the number of defined expectations
func (m *AuthRepositoryMock) MinimockFindByEmailDone() bool {
	if m.FindByEmailMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.FindByEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.FindByEmailMock.invocationsDone()
}

// MinimockFindByEmailInspect logs each unmet expectation
func (m *AuthRepositoryMock) MinimockFindByEmailInspect() {
	for _, e := range m.FindByEmailMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthRepositoryMock.FindByEmail at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterFindByEmailCounter := mm_atomic.LoadUint64(&m.afterFindByEmailCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.FindByEmailMock.defaultExpectation != nil && afterFindByEmailCounter < 1 {
		if m.FindByEmailMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to AuthRepositoryMock.FindByEmail at\n%s", m.FindByEmailMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to AuthRepositoryMock.FindByEmail at\n%s with params: %#v", m.FindByEmailMock.defaultExpectation.expectationOrigins.origin, *m.FindByEmailMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFindByEmail != nil && afterFindByEmailCounter < 1 {
		m.t.Errorf("Expected call to AuthRepositoryMock.FindByEmail at\n%s", m.funcFindByEmailOrigin)
	}

	if !m.FindByEmailMock.invocationsDone() && afterFindByEmailCounter > 0 {
		m.t.Errorf("Expected %d calls to AuthRepositoryMock.FindByEmail at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.FindByEmailMock.expectedInvocations), m.FindByEmailMock.expectedInvocationsOrigin, afterFindByEmailCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateUserInspect()

			m.MinimockFindByEmailInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateUserDone() &&
		m.MinimockFindByEmailDone()
}
