// Code generated by http://github.com/gojuno/minimock (v3.4.7). DO NOT EDIT.

package service

//go:generate minimock -i github.com/alonsoF100/authorization-service/internal/service.UserRepository -o user_repository_mock_test.go -n UserRepositoryMock -p service

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/alonsoF100/authorization-service/internal/models"
	"github.com/gojuno/minimock/v3"
)

// UserRepositoryMock implements UserRepository
type UserRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcDeleteUser          func(ctx context.Context, userID string) (err error)
	funcDeleteUserOrigin    string
	inspectFuncDeleteUser   func(ctx context.Context, userID string)
	afterDeleteUserCounter  uint64
	beforeDeleteUserCounter uint64
	DeleteUserMock          mUserRepositoryMockDeleteUser

	funcFindByID          func(ctx context.Context, userID string) (up1 *models.User, err error)
	funcFindByIDOrigin    string
	inspectFuncFindByID   func(ctx context.Context, userID string)
	afterFindByIDCounter  uint64
	beforeFindByIDCounter uint64
	FindByIDMock          mUserRepositoryMockFindByID
}

// NewUserRepositoryMock returns a mock for UserRepository
func NewUserRepositoryMock(t minimock.Tester) *UserRepositoryMock {
	m := &UserRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.DeleteUserMock = mUserRepositoryMockDeleteUser{mock: m}
	m.DeleteUserMock.callArgs = []*UserRepositoryMockDeleteUserParams{}

	m.FindByIDMock = mUserRepositoryMockFindByID{mock: m}
	m.FindByIDMock.callArgs = []*UserRepositoryMockFindByIDParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mUserRepositoryMockDeleteUser struct {
	optional           bool
	mock               *UserRepositoryMock
	defaultExpectation *UserRepositoryMockDeleteUserExpectation
	expectations       []*UserRepositoryMockDeleteUserExpectation

	callArgs []*UserRepositoryMockDeleteUserParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserRepositoryMockDeleteUserExpectation specifies expectation struct of the UserRepository.DeleteUser
type UserRepositoryMockDeleteUserExpectation struct {
	mock               *UserRepositoryMock
	params             *UserRepositoryMockDeleteUserParams
	paramPtrs          *UserRepositoryMockDeleteUserParamPtrs
	expectationOrigins UserRepositoryMockDeleteUserExpectationOrigins
	results            *UserRepositoryMockDeleteUserResults
	returnOrigin       string
	Counter            uint64
}

// UserRepositoryMockDeleteUserParams contains parameters of the UserRepository.DeleteUser
type UserRepositoryMockDeleteUserParams struct {
	ctx    context.Context
	userID string
}

// UserRepositoryMockDeleteUserParamPtrs contains pointers to parameters of the UserRepository.DeleteUser
type UserRepositoryMockDeleteUserParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// UserRepositoryMockDeleteUserResults contains results of the UserRepository.DeleteUser
type UserRepositoryMockDeleteUserResults struct {
	err error
}

// UserRepositoryMockDeleteUserOrigins contains origins of expectations of the UserRepository.DeleteUser
type UserRepositoryMockDeleteUserExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteUser *mUserRepositoryMockDeleteUser) Optional() *mUserRepositoryMockDeleteUser {
	mmDeleteUser.optional = true
	return mmDeleteUser
}

// Expect sets up expected params for UserRepository.DeleteUser
func (mmDeleteUser *mUserRepositoryMockDeleteUser) Expect(ctx context.Context, userID string) *mUserRepositoryMockDeleteUser {
	if mmDeleteUser.mock.funcDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("UserRepositoryMock.DeleteUser mock is already set by Set")
	}

	if mmDeleteUser.defaultExpectation == nil {
		mmDeleteUser.defaultExpectation = &UserRepositoryMockDeleteUserExpectation{}
	}

	if mmDeleteUser.defaultExpectation.paramPtrs != nil {
		mmDeleteUser.mock.t.Fatalf("UserRepositoryMock.DeleteUser mock is already set by ExpectParams functions")
	}

	mmDeleteUser.defaultExpectation.params = &UserRepositoryMockDeleteUserParams{ctx, userID}
	mmDeleteUser.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteUser.expectations {
		if minimock.Equal(e.params, mmDeleteUser.defaultExpectation.params) {
			mmDeleteUser.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteUser.defaultExpectation.params)
		}
	}

	return mmDeleteUser
}

// ExpectCtxParam1 sets up expected param ctx for UserRepository.DeleteUser
func (mmDeleteUser *mUserRepositoryMockDeleteUser) ExpectCtxParam1(ctx context.Context) *mUserRepositoryMockDeleteUser {
	if mmDeleteUser.mock.funcDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("UserRepositoryMock.DeleteUser mock is already set by Set")
	}

	if mmDeleteUser.defaultExpectation == nil {
		mmDeleteUser.defaultExpectation = &UserRepositoryMockDeleteUserExpectation{}
	}

	if mmDeleteUser.defaultExpectation.params != nil {
		mmDeleteUser.mock.t.Fatalf("UserRepositoryMock.DeleteUser mock is already set by Expect")
	}

	if mmDeleteUser.defaultExpectation.paramPtrs == nil {
		mmDeleteUser.defaultExpectation.paramPtrs = &UserRepositoryMockDeleteUserParamPtrs{}
	}
	mmDeleteUser.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteUser.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteUser
}

// ExpectUserIDParam2 sets up expected param userID for UserRepository.DeleteUser
func (mmDeleteUser *mUserRepositoryMockDeleteUser) ExpectUserIDParam2(userID string) *mUserRepositoryMockDeleteUser {
	if mmDeleteUser.mock.funcDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("UserRepositoryMock.DeleteUser mock is already set by Set")
	}

	if mmDeleteUser.defaultExpectation == nil {
		mmDeleteUser.defaultExpectation = &UserRepositoryMockDeleteUserExpectation{}
	}

	if mmDeleteUser.defaultExpectation.params != nil {
		mmDeleteUser.mock.t.Fatalf("UserRepositoryMock.DeleteUser mock is already set by Expect")
	}

	if mmDeleteUser.defaultExpectation.paramPtrs == nil {
		mmDeleteUser.defaultExpectation.paramPtrs = &UserRepositoryMockDeleteUserParamPtrs{}
	}
	mmDeleteUser.defaultExpectation.paramPtrs.userID = &userID
	mmDeleteUser.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmDeleteUser
}

// Inspect accepts an inspector function that has same arguments as the UserRepository.DeleteUser
func (mmDeleteUser *mUserRepositoryMockDeleteUser) Inspect(f func(ctx context.Context, userID string)) *mUserRepositoryMockDeleteUser {
	if mmDeleteUser.mock.inspectFuncDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("Inspect function is already set for UserRepositoryMock.DeleteUser")
	}

	mmDeleteUser.mock.inspectFuncDeleteUser = f

	return mmDeleteUser
}

// Return sets up results that will be returned by UserRepository.DeleteUser
func (mmDeleteUser *mUserRepositoryMockDeleteUser) Return(err error) *UserRepositoryMock {
	if mmDeleteUser.mock.funcDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("UserRepositoryMock.DeleteUser mock is already set by Set")
	}

	if mmDeleteUser.defaultExpectation == nil {
		mmDeleteUser.defaultExpectation = &UserRepositoryMockDeleteUserExpectation{mock: mmDeleteUser.mock}
	}
	mmDeleteUser.defaultExpectation.results = &UserRepositoryMockDeleteUserResults{err}
	mmDeleteUser.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteUser.mock
}

// Set uses given function f to mock the UserRepository.DeleteUser method
func (mmDeleteUser *mUserRepositoryMockDeleteUser) Set(f func(ctx context.Context, userID string) (err error)) *UserRepositoryMock {
	if mmDeleteUser.defaultExpectation != nil {
		mmDeleteUser.mock.t.Fatalf("Default expectation is already set for the UserRepository.DeleteUser method")
	}

	if len(mmDeleteUser.expectations) > 0 {
		mmDeleteUser.mock.t.Fatalf("Some expectations are already set for the UserRepository.DeleteUser method")
	}

	mmDeleteUser.mock.funcDeleteUser = f
	mmDeleteUser.mock.funcDeleteUserOrigin = minimock.CallerInfo(1)
	return mmDeleteUser.mock
}

// When sets expectation for the UserRepository.DeleteUser which will trigger the result defined by the following
// Then helper
func (mmDeleteUser *mUserRepositoryMockDeleteUser) When(ctx context.Context, userID string) *UserRepositoryMockDeleteUserExpectation {
	if mmDeleteUser.mock.funcDeleteUser != nil {
		mmDeleteUser.mock.t.Fatalf("UserRepositoryMock.DeleteUser mock is already set by Set")
	}

	expectation := &UserRepositoryMockDeleteUserExpectation{
		mock:               mmDeleteUser.mock,
		params:             &UserRepositoryMockDeleteUserParams{ctx, userID},
		expectationOrigins: UserRepositoryMockDeleteUserExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteUser.expectations = append(mmDeleteUser.expectations, expectation)
	return expectation
}

// Then sets up UserRepository.DeleteUser return parameters for the expectation previously defined by the When method
func (e *UserRepositoryMockDeleteUserExpectation) Then(err error) *UserRepositoryMock {
	e.results = &UserRepositoryMockDeleteUserResults{err}
	return e.mock
}

// Times sets number of times UserRepository.DeleteUser should be invoked
func (mmDeleteUser *mUserRepositoryMockDeleteUser) Times(n uint64) *mUserRepositoryMockDeleteUser {
	if n == 0 {
		mmDeleteUser.mock.t.Fatalf("Times of UserRepositoryMock.DeleteUser mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteUser.expectedInvocations, n)
	mmDeleteUser.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteUser
}

func (mmDeleteUser *mUserRepositoryMockDeleteUser) invocationsDone() bool {
	if len(mmDeleteUser.expectations) == 0 && mmDeleteUser.defaultExpectation == nil && mmDeleteUser.mock.funcDeleteUser == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteUser.mock.afterDeleteUserCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteUser.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteUser implements UserRepository
func (mmDeleteUser *UserRepositoryMock) DeleteUser(ctx context.Context, userID string) (err error) {
	mm_atomic.AddUint64(&mmDeleteUser.beforeDeleteUserCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteUser.afterDeleteUserCounter, 1)

	mmDeleteUser.t.Helper()

	if mmDeleteUser.inspectFuncDeleteUser != nil {
		mmDeleteUser.inspectFuncDeleteUser(ctx, userID)
	}

	mm_params := UserRepositoryMockDeleteUserParams{ctx, userID}

	// Record call args
	mmDeleteUser.DeleteUserMock.mutex.Lock()
	mmDeleteUser.DeleteUserMock.callArgs = append(mmDeleteUser.DeleteUserMock.callArgs, &mm_params)
	mmDeleteUser.DeleteUserMock.mutex.Unlock()

	for _, e := range mmDeleteUser.DeleteUserMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteUser.DeleteUserMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteUser.DeleteUserMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteUser.DeleteUserMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteUser.DeleteUserMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryMockDeleteUserParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteUser.t.Errorf("UserRepositoryMock.DeleteUser got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteUser.DeleteUserMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmDeleteUser.t.Errorf("UserRepositoryMock.DeleteUser got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteUser.DeleteUserMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteUser.t.Errorf("UserRepositoryMock.DeleteUser got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteUser.DeleteUserMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteUser.DeleteUserMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteUser.t.Fatal("No results are set for the UserRepositoryMock.DeleteUser")
		}
		return (*mm_results).err
	}
	if mmDeleteUser.funcDeleteUser != nil {
		return mmDeleteUser.funcDeleteUser(ctx, userID)
	}
	mmDeleteUser.t.Fatalf("Unexpected call to UserRepositoryMock.DeleteUser. %v %v", ctx, userID)
	return
}

// DeleteUserAfterCounter returns a count of finished UserRepositoryMock.DeleteUser invocations
func (mmDeleteUser *UserRepositoryMock) DeleteUserAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteUser.afterDeleteUserCounter)
}

// DeleteUserBeforeCounter returns a count of UserRepositoryMock.DeleteUser invocations
func (mmDeleteUser *UserRepositoryMock) DeleteUserBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteUser.beforeDeleteUserCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryMock.DeleteUser.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteUser *mUserRepositoryMockDeleteUser) Calls() []*UserRepositoryMockDeleteUserParams {
	mmDeleteUser.mutex.RLock()

	argCopy := make([]*UserRepositoryMockDeleteUserParams, len(mmDeleteUser.callArgs))
	copy(argCopy, mmDeleteUser.callArgs)

	mmDeleteUser.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteUserDone returns true if the count of the DeleteUser invocations corresponds
// the number of defined expectations
func (m *UserRepositoryMock) MinimockDeleteUserDone() bool {
	if m.DeleteUserMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteUserMock.invocationsDone()
}

// MinimockDeleteUserInspect logs each unmet expectation
func (m *UserRepositoryMock) MinimockDeleteUserInspect() {
	for _, e := range m.DeleteUserMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryMock.DeleteUser at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteUserCounter := mm_atomic.LoadUint64(&m.afterDeleteUserCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteUserMock.defaultExpectation != nil && afterDeleteUserCounter < 1 {
		if m.DeleteUserMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserRepositoryMock.DeleteUser at\n%s", m.DeleteUserMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserRepositoryMock.DeleteUser at\n%s with params: %#v", m.DeleteUserMock.defaultExpectation.expectationOrigins.origin, *m.DeleteUserMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteUser != nil && afterDeleteUserCounter < 1 {
		m.t.Errorf("Expected call to UserRepositoryMock.DeleteUser at\n%s", m.funcDeleteUserOrigin)
	}

	if !m.DeleteUserMock.invocationsDone() && afterDeleteUserCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryMock.DeleteUser at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteUserMock.expectedInvocations), m.DeleteUserMock.expectedInvocationsOrigin, afterDeleteUserCounter)
	}
}

type mUserRepositoryMockFindByID struct {
	optional           bool
	mock               *UserRepositoryMock
	defaultExpectation *UserRepositoryMockFindByIDExpectation
	expectations       []*UserRepositoryMockFindByIDExpectation

	callArgs []*UserRepositoryMockFindByIDParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// UserRepositoryMockFindByIDExpectation specifies expectation struct of the UserRepository.FindByID
type UserRepositoryMockFindByIDExpectation struct {
	mock               *UserRepositoryMock
	params             *UserRepositoryMockFindByIDParams
	paramPtrs          *UserRepositoryMockFindByIDParamPtrs
	expectationOrigins UserRepositoryMockFindByIDExpectationOrigins
	results            *UserRepositoryMockFindByIDResults
	returnOrigin       string
	Counter            uint64
}

// UserRepositoryMockFindByIDParams contains parameters of the UserRepository.FindByID
type UserRepositoryMockFindByIDParams struct {
	ctx    context.Context
	userID string
}

// UserRepositoryMockFindByIDParamPtrs contains pointers to parameters of the UserRepository.FindByID
type UserRepositoryMockFindByIDParamPtrs struct {
	ctx    *context.Context
	userID *string
}

// UserRepositoryMockFindByIDResults contains results of the UserRepository.FindByID
type UserRepositoryMockFindByIDResults struct {
	up1 *models.User
	err error
}

// UserRepositoryMockFindByIDOrigins contains origins of expectations of the UserRepository.FindByID
type UserRepositoryMockFindByIDExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserID string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmFindByID *mUserRepositoryMockFindByID) Optional() *mUserRepositoryMockFindByID {
	mmFindByID.optional = true
	return mmFindByID
}

// Expect sets up expected params for UserRepository.FindByID
func (mmFindByID *mUserRepositoryMockFindByID) Expect(ctx context.Context, userID string) *mUserRepositoryMockFindByID {
	if mmFindByID.mock.funcFindByID != nil {
		mmFindByID.mock.t.Fatalf("UserRepositoryMock.FindByID mock is already set by Set")
	}

	if mmFindByID.defaultExpectation == nil {
		mmFindByID.defaultExpectation = &UserRepositoryMockFindByIDExpectation{}
	}

	if mmFindByID.defaultExpectation.paramPtrs != nil {
		mmFindByID.mock.t.Fatalf("UserRepositoryMock.FindByID mock is already set by ExpectParams functions")
	}

	mmFindByID.defaultExpectation.params = &UserRepositoryMockFindByIDParams{ctx, userID}
	mmFindByID.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmFindByID.expectations {
		if minimock.Equal(e.params, mmFindByID.defaultExpectation.params) {
			mmFindByID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmFindByID.defaultExpectation.params)
		}
	}

	return mmFindByID
}

// ExpectCtxParam1 sets up expected param ctx for UserRepository.FindByID
func (mmFindByID *mUserRepositoryMockFindByID) ExpectCtxParam1(ctx context.Context) *mUserRepositoryMockFindByID {
	if mmFindByID.mock.funcFindByID != nil {
		mmFindByID.mock.t.Fatalf("UserRepositoryMock.FindByID mock is already set by Set")
	}

	if mmFindByID.defaultExpectation == nil {
		mmFindByID.defaultExpectation = &UserRepositoryMockFindByIDExpectation{}
	}

	if mmFindByID.defaultExpectation.params != nil {
		mmFindByID.mock.t.Fatalf("UserRepositoryMock.FindByID mock is already set by Expect")
	}

	if mmFindByID.defaultExpectation.paramPtrs == nil {
		mmFindByID.defaultExpectation.paramPtrs = &UserRepositoryMockFindByIDParamPtrs{}
	}
	mmFindByID.defaultExpectation.paramPtrs.ctx = &ctx
	mmFindByID.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmFindByID
}

// ExpectUserIDParam2 sets up expected param userID for UserRepository.FindByID
func (mmFindByID *mUserRepositoryMockFindByID) ExpectUserIDParam2(userID string) *mUserRepositoryMockFindByID {
	if mmFindByID.mock.funcFindByID != nil {
		mmFindByID.mock.t.Fatalf("UserRepositoryMock.FindByID mock is already set by Set")
	}

	if mmFindByID.defaultExpectation == nil {
		mmFindByID.defaultExpectation = &UserRepositoryMockFindByIDExpectation{}
	}

	if mmFindByID.defaultExpectation.params != nil {
		mmFindByID.mock.t.Fatalf("UserRepositoryMock.FindByID mock is already set by Expect")
	}

	if mmFindByID.defaultExpectation.paramPtrs == nil {
		mmFindByID.defaultExpectation.paramPtrs = &UserRepositoryMockFindByIDParamPtrs{}
	}
	mmFindByID.defaultExpectation.paramPtrs.userID = &userID
	mmFindByID.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmFindByID
}

// Inspect accepts an inspector function that has same arguments as the UserRepository.FindByID
func (mmFindByID *mUserRepositoryMockFindByID) Inspect(f func(ctx context.Context, userID string)) *mUserRepositoryMockFindByID {
	if mmFindByID.mock.inspectFuncFindByID != nil {
		mmFindByID.mock.t.Fatalf("Inspect function is already set for UserRepositoryMock.FindByID")
	}

	mmFindByID.mock.inspectFuncFindByID = f

	return mmFindByID
}

// Return sets up results that will be returned by UserRepository.FindByID
func (mmFindByID *mUserRepositoryMockFindByID) Return(up1 *models.User, err error) *UserRepositoryMock {
	if mmFindByID.mock.funcFindByID != nil {
		mmFindByID.mock.t.Fatalf("UserRepositoryMock.FindByID mock is already set by Set")
	}

	if mmFindByID.defaultExpectation == nil {
		mmFindByID.defaultExpectation = &UserRepositoryMockFindByIDExpectation{mock: mmFindByID.mock}
	}
	mmFindByID.defaultExpectation.results = &UserRepositoryMockFindByIDResults{up1, err}
	mmFindByID.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmFindByID.mock
}

// Set uses given function f to mock the UserRepository.FindByID method
func (mmFindByID *mUserRepositoryMockFindByID) Set(f func(ctx context.Context, userID string) (up1 *models.User, err error)) *UserRepositoryMock {
	if mmFindByID.defaultExpectation != nil {
		mmFindByID.mock.t.Fatalf("Default expectation is already set for the UserRepository.FindByID method")
	}

	if len(mmFindByID.expectations) > 0 {
		mmFindByID.mock.t.Fatalf("Some expectations are already set for the UserRepository.FindByID method")
	}

	mmFindByID.mock.funcFindByID = f
	mmFindByID.mock.funcFindByIDOrigin = minimock.CallerInfo(1)
	return mmFindByID.mock
}

// When sets expectation for the UserRepository.FindByID which will trigger the result defined by the following
// Then helper
func (mmFindByID *mUserRepositoryMockFindByID) When(ctx context.Context, userID string) *UserRepositoryMockFindByIDExpectation {
	if mmFindByID.mock.funcFindByID != nil {
		mmFindByID.mock.t.Fatalf("UserRepositoryMock.FindByID mock is already set by Set")
	}

	expectation := &UserRepositoryMockFindByIDExpectation{
		mock:               mmFindByID.mock,
		params:             &UserRepositoryMockFindByIDParams{ctx, userID},
		expectationOrigins: UserRepositoryMockFindByIDExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmFindByID.expectations = append(mmFindByID.expectations, expectation)
	return expectation
}

// Then sets up UserRepository.FindByID return parameters for the expectation previously defined by the When method
func (e *UserRepositoryMockFindByIDExpectation) Then(up1 *models.User, err error) *UserRepositoryMock {
	e.results = &UserRepositoryMockFindByIDResults{up1, err}
	return e.mock
}

// Times sets number of times UserRepository.FindByID should be invoked
func (mmFindByID *mUserRepositoryMockFindByID) Times(n uint64) *mUserRepositoryMockFindByID {
	if n == 0 {
		mmFindByID.mock.t.Fatalf("Times of UserRepositoryMock.FindByID mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmFindByID.expectedInvocations, n)
	mmFindByID.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmFindByID
}

func (mmFindByID *mUserRepositoryMockFindByID) invocationsDone() bool {
	if len(mmFindByID.expectations) == 0 && mmFindByID.defaultExpectation == nil && mmFindByID.mock.funcFindByID == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmFindByID.mock.afterFindByIDCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmFindByID.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// FindByID implements UserRepository
func (mmFindByID *UserRepositoryMock) FindByID(ctx context.Context, userID string) (up1 *models.User, err error) {
	mm_atomic.AddUint64(&mmFindByID.beforeFindByIDCounter, 1)
	defer mm_atomic.AddUint64(&mmFindByID.afterFindByIDCounter, 1)

	mmFindByID.t.Helper()

	if mmFindByID.inspectFuncFindByID != nil {
		mmFindByID.inspectFuncFindByID(ctx, userID)
	}

	mm_params := UserRepositoryMockFindByIDParams{ctx, userID}

	// Record call args
	mmFindByID.FindByIDMock.mutex.Lock()
	mmFindByID.FindByIDMock.callArgs = append(mmFindByID.FindByIDMock.callArgs, &mm_params)
	mmFindByID.FindByIDMock.mutex.Unlock()

	for _, e := range mmFindByID.FindByIDMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmFindByID.FindByIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmFindByID.FindByIDMock.defaultExpectation.Counter, 1)
		mm_want := mmFindByID.FindByIDMock.defaultExpectation.params
		mm_want_ptrs := mmFindByID.FindByIDMock.defaultExpectation.paramPtrs

		mm_got := UserRepositoryMockFindByIDParams{ctx, userID}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmFindByID.t.Errorf("UserRepositoryMock.FindByID got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFindByID.FindByIDMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmFindByID.t.Errorf("UserRepositoryMock.FindByID got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmFindByID.FindByIDMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmFindByID.t.Errorf("UserRepositoryMock.FindByID got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmFindByID.FindByIDMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmFindByID.FindByIDMock.defaultExpectation.results
		if mm_results == nil {
			mmFindByID.t.Fatal("No results are set for the UserRepositoryMock.FindByID")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmFindByID.funcFindByID != nil {
		return mmFindByID.funcFindByID(ctx, userID)
	}
	mmFindByID.t.Fatalf("Unexpected call to UserRepositoryMock.FindByID. %v %v", ctx, userID)
	return
}

// FindByIDAfterCounter returns a count of finished UserRepositoryMock.FindByID invocations
func (mmFindByID *UserRepositoryMock) FindByIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFindByID.afterFindByIDCounter)
}

// FindByIDBeforeCounter returns a count of UserRepositoryMock.FindByID invocations
func (mmFindByID *UserRepositoryMock) FindByIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmFindByID.beforeFindByIDCounter)
}

// Calls returns a list of arguments used in each call to UserRepositoryMock.FindByID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmFindByID *mUserRepositoryMockFindByID) Calls() []*UserRepositoryMockFindByIDParams {
	mmFindByID.mutex.RLock()

	argCopy := make([]*UserRepositoryMockFindByIDParams, len(mmFindByID.callArgs))
	copy(argCopy, mmFindByID.callArgs)

	mmFindByID.mutex.RUnlock()

	return argCopy
}

// MinimockFindByIDDone returns true if the count of the FindByID invocations corresponds
// the number of defined expectations
func (m *UserRepositoryMock) MinimockFindByIDDone() bool {
	if m.FindByIDMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.FindByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.FindByIDMock.invocationsDone()
}

// MinimockFindByIDInspect logs each unmet expectation
func (m *UserRepositoryMock) MinimockFindByIDInspect() {
	for _, e := range m.FindByIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to UserRepositoryMock.FindByID at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterFindByIDCounter := mm_atomic.LoadUint64(&m.afterFindByIDCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.FindByIDMock.defaultExpectation != nil && afterFindByIDCounter < 1 {
		if m.FindByIDMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to UserRepositoryMock.FindByID at\n%s", m.FindByIDMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to UserRepositoryMock.FindByID at\n%s with params: %#v", m.FindByIDMock.defaultExpectation.expectationOrigins.origin, *m.FindByIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcFindByID != nil && afterFindByIDCounter < 1 {
		m.t.Errorf("Expected call to UserRepositoryMock.FindByID at\n%s", m.funcFindByIDOrigin)
	}

	if !m.FindByIDMock.invocationsDone() && afterFindByIDCounter > 0 {
		m.t.Errorf("Expected %d calls to UserRepositoryMock.FindByID at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.FindByIDMock.expectedInvocations), m.FindByIDMock.expectedInvocationsOrigin, afterFindByIDCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *UserRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockDeleteUserInspect()

			m.MinimockFindByIDInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *UserRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *UserRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockDeleteUserDone() &&
		m.MinimockFindByIDDone()
}
